
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-hr-backend
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - APP_NAME=${APP_NAME:-AI HR System}
      - VERSION=${VERSION:-1.0.0}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-false}
      - HOST=0.0.0.0
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./test.db}
      - LLM_VENDOR=${LLM_VENDOR:-groq}
      - LLM_MODEL=${LLM_MODEL:-qwen/qwen3-32b}
      - ALLOWED_ORIGINS=["http://localhost:8501","http://localhost:3000"]
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    networks:
      - ai-hr-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-hr-frontend
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=${API_BASE_URL:-http://backend:8000}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-false}
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - ai-hr-network
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-hr-network:
    driver: bridge

volumes:
  app-data:
